### ISSUE TITLE
TreeCount does not support Django 2.0

### ISSUE THREAD

**Issue by C4ptainCrunch** [t00n/TreeCount#17]
At least, every model foreign key misses the now mandatory `on_delete` argument but there might be more incompatibilities. 
See the [release notes of Django 2.0](https://docs.djangoproject.com/en/2.0/releases/2.0/) for more info.

**Comment by titouanc** [comment]
Do we really care ?

**Comment by t00n** [comment]
If you want to do it, go for it ;)

**Comment by t00n** [comment]
fixed in https://github.com/t00n/TreeCount/pull/19
